### ISSUE TITLE
文档似乎有很多处和实际代码使用不一样的地方

### ISSUE THREAD

**Issue by liutaihua** [bigplum/lua-resty-mongol#5]
比如文档中说的conn:settimeout(msec), 实际上代码内写的是conn:set_timeout(msec).

文档内说的conn:cmd这个mothod没有，引用会报nil错误.

**Comment by zhangzhihai** [comment]
帮看看关于sort使用的问题吗，使用query查询如何使用sort排序呀，指的不是查询出来的结果排序
